#3 JSONのPOST
TechTMG/TMG-ToDo pull request #7
Opened 2020-07-13 16:35 UTC by granatetanarg

api.pyにPOST用のroutingを追加
db.pyにSQLにINSERTする関数を追加

2020-07-13 16:40 UTC, thimi0412 approved these changes
![LGTM](https://i.lgtm.fun/web.gif)

2020-07-13 17:01 UTC, granatetanarg commented
@Satorino01 @rofutocgm 
お時間があるときでよろしいので、レビューの方お願いしてもよろしいでしょうか

2020-07-15 11:44 UTC, Satorino01 requested changes
レビューしました。
get_alltaskの仕様は問題ありません。ただ、postの実装に懸念点があります。どんなリクエストでも'COMPLETE'と返されます。postに簡単なエラーハンドリングを実装してください。別タスクでいいですが後々カラムごとのvalidation や HTTPステータスコードを返却するように処理を追加していきましょう。

2020-07-15 11:44 UTC, Satorino01 commented on api.py
> +    return complete
エラー出力とエラーハンドリングを簡単でいいので記述しましょう。insertに失敗したら'FAIL'と出力するだけでも結構です。今現在ではPOSTが失敗しても'COMPLETE'と返却されるため非常に紛らわしくなってしまいます。

2020-07-15 11:54 UTC, Satorino01 commented on api.py
> +    return complete
あと `complete `がただの中間変数になっているのでこの処理なら
```
 complete = "COMPLETE"
 return complete
```
ではなく
```
 return "COMPLETE"
```
でいいと思います！

2020-07-15 12:05 UTC, Satorino01 reviewed
追加で

2020-07-15 12:05 UTC, Satorino01 commented on api.py
> +    post_task(post_json)
post_task()側で下記のように値を返却していますがこちらの行で値を拾っていません。
https://github.com/TechTMG/TMG-ToDo/blob/9d68749cfe26d9f5e31d3948a3fefb9ced3eac50/db.py#L57
拾ってあげましょう。そうすればエラー出力も書きやすくなるはずです。

2020-07-15 14:07 UTC, Satorino01 approved these changes
エラー出力の仕様は満たされています。LGTMです！中間変数が気になるので、こちらのブランチでも次のタスクでもいいので修正しておいてください。上記で `result = post_task(post_json)`を書くように言ってしまいましたが言葉たらずでした。ごめんなさい。中間変数を許す状況やチームはあんまりないので消せるところは消すように心がけてください。

2020-07-15 14:07 UTC, Satorino01 commented on api.py
> +    result = post_task(post_json)
resultが中間変数になってしまっているので

```suggestion
    return post_task(post_json)
```
　でいいかな

2020-07-15 14:07 UTC, Satorino01 commented on api.py
> +    return result
```suggestion
    
```

2020-07-15 14:26 UTC, merged